/* eslint-disable */
/**
 * Minimal hand-written stand-in for Convex generated api module.
 * Regenerated by `npx convex dev` in a properly authenticated environment.
 */
export const devices: any;
export const sessions: any;
export const settings: any;
export const seed: any;
export const anyApi: any;
declare const _api: any;
export default _api;
