/* eslint-disable */
/**
 * Minimal hand-written stand-in for Convex generated api module.
 * Regenerated by `npx convex dev` in a properly authenticated environment.
 */
export const anyApi = new Proxy(
  {},
  {
    get() {
      return () => null;
    },
  },
);

export const devices = anyApi.devices;
export const sessions = anyApi.sessions;
export const settings = anyApi.settings;
export const seed = anyApi.seed;
