/* eslint-disable */
/**
 * Minimal hand-written stand-in for Convex generated server types.
 * Regenerated by `npx convex dev` in a properly authenticated environment.
 */
declare module "./_generated/server" {
  export type QueryCtx = any;
  export type MutationCtx = any;
  export function query(a: any, b: any): any;
  export function mutation(a: any, b: any): any;
  export function internalQuery(a: any, b: any): any;
  export function internalMutation(a: any, b: any): any;
  export function action(a: any, b: any): any;
}
